//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOINSP_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid companyid { get; set; }
        public string BedrijfsNaam { get; set; }
        public string BedrijfsEmail { get; set; }
        public string BedrijfsAdres { get; set; }
        public string BedrijfsPostcode { get; set; }
        public string BedrijfsNummer { get; set; }
        public string BedrijfsGemeente { get; set; }
        public string BedrijfsWijk { get; set; }
        public string BedrijfsGemeenteCode { get; set; }
        public decimal BedrijfsLat { get; set; }
        public decimal BedrijfsLon { get; set; }
        public string BedrijfsPortalKey { get; set; }
    }
}
